### ISSUE TITLE
Please fix

### ISSUE THREAD

**Issue by mean-cj** [rogeriopradoj/composer-php52-github#1]
[ErrorException]
  Declaration of RogerioPradoJ\Composer52\AutoloadGenerator::getAutoloadRealFile() should be compatible with that of Composer\Autoload\AutoloadGenerator::getAutoloadRealFile()

**Comment by rogeriopradoj** [comment]
Hi, @mean-cj , sorry for taking so long.

Please, don't use this fork. Use the official one: https://packagist.org/packages/xrstf/composer-php52, ok?

Thanks for understanding.
